.catalog:
  name: "Route53 DNS"
  version: "v0.4.0-rancher1"
  description: "Rancher External DNS service powered by Amazon Route53. Requires Rancher version 0.44.0"
  minimum_rancher_version: v0.44.0
  maximum_rancher_version: v1.1.99
  questions:
    - variable: "AWS_ACCESS_KEY"
      label: "AWS access key"
      description: "Access key to your AWS account"
      type: "string"
      required: true
    - variable: "AWS_SECRET_KEY"
      label: "AWS secret key"
      description: "Secret key to your AWS account"
      type: "string"
      required: true
    - variable: "AWS_REGION"
      label: "AWS region"
      description: "AWS region name"
      type: "string"
      default: "us-west-2"
      required: true
    - variable: "TTL"
      label: "TTL"
      description: "The resource record cache time to live (TTL), in seconds"
      type: "int"
      default: 299
      required: false
    - variable: "ROOT_DOMAIN"
      label: "Hosted zone name"
      description: "Route53 hosted zone name (zone has to be pre-created). DNS entries will be created for <service>.<stack>.<environment>.<hosted zone>"
      type: "string"
      required: true
    - variable: "ROUTE53_ZONE_ID"
      label: "Hosted zone ID"
      description: "If there are multiple zones with the same name, you additionally need to specify the ID of the hosted zone to be used."
      type: "string"
      required: false

route53:
  health_check:
    port: 1000
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
