.catalog:
  name: "Rancher NFS"
  version: "0.3.0"
  description: |
    Docker volume plugin for NFS
  minimum_rancher_version: v1.6.0-rc1
  questions:
  - variable: "NFS_SERVER"
    description: "IP or hostname of the default NFS Server"
    label: "NFS Server"
    required: true
    type: "string"
  - variable: "MOUNT_DIR"
    label: "Export Directory"
    description: "The default exported directory"
    type: "string"
    required: true
  - variable: "MOUNT_OPTS"
    label: "Mount Options"
    description: "Comma delimited list of default mount options, for example: 'proto=udp'. Do not specify `nfsvers` option, it will be ignored."
    type: "string"
  - variable: "NFS_VERS"
    label: NFS Version
    description: The NFS version to use
    type: enum
    required: true
    default: nfsvers=4
    options:
    - nfsvers=4
  - variable: RANCHER_DEBUG
    label: Debug Mode
    type: enum
    description: Enable or disable verbose logging
    default: false
    options:
    - true
    - false
nfs-driver:
  storage_driver:
    name: rancher-nfs
    scope: environment
    volume_access_mode: multiHostRW
