.catalog:
  name: "Route53 DNS"
  version: "v0.1.5-rancher1"
  description: "Rancher External DNS service powered by Amazon Route53. Requires Rancher version 0.44.0"
  maximum_rancher_version: v1.1.99
  questions:
    - variable: "AWS_ACCESS_KEY"
      label: "AWS access key"
      description: "Access key to your AWS account"
      type: "string"
      required: true
    - variable: "AWS_SECRET_KEY"
      label: "AWS secret key"
      description: "Secret key to your AWS account"
      type: "string"
      required: true
    - variable: "AWS_REGION"
      label: "AWS region"
      description: "AWS region name"
      type: "string"
      default: "us-west-2"
      required: true
    - variable: "ROOT_DOMAIN"
      label: "Hosted zone"
      description: "Route53 hosted zone (has to be pre-created). DNS entries will be created for <service>.<stack>.<environment>.<hosted zone>"
      type: "string"
      required: true

route53:
  health_check:
    port: 1000
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
