.catalog:
  name: "GlusterFS"
  version: "3.7.5-rancher1"
  description: "Gluster FS (3x) replicated volume"
  questions:
    - variable: "VOLUME_NAME"
      description: "Name to give the Gluster volume"
      label: "Volume Name"
      required: true
      default: "my_vol"
      type: "string"
glusterfs-server:
  scale: 3
  metadata:
    volume_name: "${VOLUME_NAME}"
